services:
  - type: web
    name: humanity-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn apps.api.core_main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: HUMANITY_SIGNING_SECRET
        generateValue: true
      - key: HUMANITY_DB_PATH
        value: /var/data/humanity.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
