name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    name: Backend (FastAPI) tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: packages/core
        run: |
          python -m pip install --upgrade pip
          pip install -e . fastapi uvicorn[standard] pytest httpx
      - name: Run pytest
        working-directory: packages/core
        run: pytest -q

  frontend:
    name: Frontend (Next.js) build & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json
      - name: Install deps
        working-directory: apps/web
        run: npm ci
      - name: Lint
        working-directory: apps/web
        run: npm run lint -- --max-warnings=0 || echo "Lint warnings present"
      - name: Build
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
        run: npm run build

  # Simple integration to ensure both can be installed together (no runtime server test here)
  integration-matrix:
    name: Integration matrix smoke
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11']
        node: ['20']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install backend deps
        working-directory: packages/core
        run: |
          pip install -e . fastapi uvicorn[standard]
      - name: Install frontend deps
        working-directory: apps/web
        run: npm ci
      - name: Type check & build frontend
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
        run: npm run build
